// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjoonllcjbiwkzzhskum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhqb29ubGxjamJpd2t6emhza3VtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MjY2MDUsImV4cCI6MjA2MzUwMjYwNX0.EBQbTFx7_ViaPOAR0ZIoBVwvnqDa9J75-fyhsdwxTY0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);